# Build Options
#   comment out to disable the options.
#

MCU = STM32F103
MCU_LDSCRIPT = STM32F103xB_uf2
FIRMWARE_FORMAT = uf2
BOARD = GENERIC_STM32_F103XB

# Bootloader selection
BOOTLOADER = custom

KEYBOARD_SHARED_EP = yes
LTO_ENABLE = yes

OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
SRC += uf2_boot.c
SRC += analog.c

# 驱动设置
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = pwm
SERIAL_DRIVER = usart
AUDIO_DRIVER = pwm_hardware
OLED_DRIVER = SSD1306
POINTING_DEVICE_DRIVER = analog_joystick
JOYSTICK_DRIVER = analog


# 打开功能
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
AUDIO_ENABLE = yes
OLED_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RADIAL_CONTROLLER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
RGB_MATRIX_CONTROL_ENABLE = yes
UNDERGLOW_RGB_MATRIX_ENABLE = yes
RGB_INDICATORS_ENABLE = yes
RGB_INDICATORS = dynamic
OPENRGB_ENABLE = yes
SIGNALRGB_ENABLE = yes
VIA_ENABLE = yes
VIA_CUSTOM_KEYCODE_ENABLE = yes
VIA_CUSTOM_CONTROL_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
JOYSTICK_ENABLE = yes

# 关闭功能
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
RGBLIGHT_ENABLE = no



