SERIAL_DRIVER = vendor
WS2812_DRIVER = vendor

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

SRC += lvgl_helpers.c \
	   display.c


# AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
# 打开震动
HAPTIC_ENABLE = yes
# HAPTIC_DRIVER += DRV2605L
HAPTIC_DRIVER += SOLENOID


# 加入zhaqian设置
# ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
# RADIAL_CONTROLLER_ENABLE = yes
# RGB_MATRIX_CUSTOM_KB = yes
# RGB_MATRIX_CONTROL_ENABLE = yes
# UNDERGLOW_RGB_MATRIX_ENABLE = yes
# RGB_INDICATORS_ENABLE = yes
# RGB_INDICATORS = dynamic
OPENRGB_ENABLE = yes
# SIGNALRGB_ENABLE = yes
VIA_ENABLE = yes
VIA_CUSTOM_KEYCODE_ENABLE = yes
VIA_CUSTOM_CONTROL_ENABLE = yes
MAGIC_SETTINGS_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
DYNAMIC_TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_COMBOS_ENABLE = yes
AUTO_SWITCH_LAYERS_ENABLE = yes
