
WS2812_DRIVER = pwm

KEYBOARD_SHARED_EP = yes
LTO_ENABLE = yes

OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE



BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware



ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RADIAL_CONTROLLER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
RGB_MATRIX_CUSTOM_KB = yes
RGB_MATRIX_CONTROL_ENABLE = yes
UNDERGLOW_RGB_MATRIX_ENABLE = yes
RGB_INDICATORS_ENABLE = yes
RGB_INDICATORS = dynamic
OPENRGB_ENABLE = yes
SIGNALRGB_ENABLE = yes
VIA_ENABLE = yes
VIA_CUSTOM_KEYCODE_ENABLE = yes
VIA_CUSTOM_CONTROL_ENABLE = yes


